---
format: html
---

::: {.main-container}

::: {.resume-card}

::: {.resume-header-flex}
[Download PDF Resume](resume.pdf){.btn-blue-download target="_blank"}
:::

::: {.resume-section-title}
EDUCATION
:::

::: {.resume-row}
[B.S., Engineering (Mechatronics Specialization)]{.resume-bold-title}

[Expected May 2028]{.resume-date}
:::
::: {.resume-subtext}
Harvey Mudd College — Claremont, California, USA
:::

**Major GPA:** 4.0 / 4.0 | **Cumulative GPA:** 3.918 / 4.0 | **Dean's List** (all graded semesters)

::: {.resume-general-text}
**Relevant Coursework:** 
Microprocessor Systems: Design & Application; Digital Electronics & Computer Engineering; Continuum Mechanics; Electrical & Magnetic Circuits/Devices; Advanced Systems Engineering; Experimental Engineering; Engineering Systems; Intro to Engineering Design/Manufacturing; Applied Math for Engineering; Probability/Stats for Engineers; Intro to Computer Science
:::

::: {.resume-section-title}
AWARDS AND ACHIEVEMENTS
:::

::: {.resume-row}
[Tau Beta Pi Member (United States Engineering Honours Society, Top 12.5% of Junior Class)]{.resume-bold-title}

[2026 – Present]{.resume-date}
:::

::: {.resume-row}
[Harvey Mudd Merit Scholarship (Top 15% of Entering Class)]{.resume-bold-title}

[2024 – Present]{.resume-date}
:::

::: {.resume-section-title}
WORK EXPERIENCE
:::

::: {.resume-row}
[R&D Manufacturing Contractor]{.resume-bold-title}

[Aug 2026 – Present]{.resume-date}
:::
::: {.resume-subtext}
Medtronic MiniMed (Through Harvey Mudd College Clinic Program)
:::

* Optimized Continuous Glucose Monitor sensor manufacturing process, reduced cycle time from __ to __ hrs
* Prototyped & tested a sensor clamping fixture, prevented sensor damage & improved operator ergonomics
* Performed materials analysis & testing, met ISO 7 classifications & withstood corrosive baths during 24/5 use

::: {.resume-row}
[Paid Engineering Intern]{.resume-bold-title}

[Jul 2026 – Aug 2026]{.resume-date}
:::
::: {.resume-subtext}
Cathay Pacific, Hong Kong
:::

* Developed a cross-company maintenance Power App; cut daily task time from 1hr+ to 24min (100% adoption)
* Built a Power BI automated predictive model, optimized servicing for 13 cabin layouts under operational limits
* Improved aircraft regulatory compliance by analyzing Acceptable Deferred Defects in Ultramain & Skywise
* Co-developed an Ultralytics YOLO computer vision model to detect cabin defects & automate inspections

::: {.resume-row}
[Undergraduate Student Researcher]{.resume-bold-title}

[Jan 2026 – Present]{.resume-date}
:::
::: {.resume-subtext}
Flow Imaging Lab at Mudd, Dept. of Engineering, Harvey Mudd College
:::

* Designed & manufactured a mechanical 3-axis calibrator for a live class-4 laser for Particle Image Velocimetry
* Processed 6-axis load cell data using MATLAB to quantify thrust generated by a biomimetic fish fin
* Programmed a PI-controlled rotational degree of freedom for the fin; troubleshot load cell/motor interference
* Managed waterjet safety & maintenance; advised team of 5 on machining processes to eliminate fin defects

::: {.resume-row}
[Lab Teaching Assistant / Lab Improver]{.resume-bold-title}

[Aug 2025 – Present]{.resume-date}
:::
::: {.resume-subtext}
Intro to Engineering Design/Manufacturing, Harvey Mudd College
:::

* Taught 20+ students SolidWorks, CAD, motion studies, finite element analysis, prototyping, material selection
* Reviewed technical drawings for manufacturing; final products used in research labs, courses, school services
* Authored 5 SolidWorks tutorials teaching feature logic and software troubleshooting, used by 60+ students
* Pioneered new student role, eliminated continuity errors between teachings & deliverable expectations

::: {.resume-row}
[Repair Steward]{.resume-bold-title}

[Jan 2025 – Present]{.resume-date}
:::
::: {.resume-subtext}
Makerspace, Harvey Mudd College
:::

* Maintained, repaired & troubleshot fabrication equipment failures; minimized downtime for 2500+ users
* Coordinated with 5 undergraduates to write/update user, safety & repair manuals & SOPs for all equipment
* Optimized services; provided remote technical support, analyzed maintenance logs, reported inconsistencies

::: {.resume-row}
[Undergraduate Student Researcher]{.resume-bold-title}

[Jan 2025 – Dec 2025]{.resume-date}
:::
::: {.resume-subtext}
HMC Biophotonics Lab, Dept. of Engineering, Harvey Mudd College
:::

* Co-developed an open-source in vivo imaging system, reduced production cost to <1% of commercial price
* Improved speckle contrast & bioluminescence imaging capabilities; device used @ Claremont McKenna College
* Devised experimental optics setups; troubleshot modules with oscilloscopes; processed images with Python

::: {.resume-row}
[Paid Student Intern]{.resume-bold-title}

[Jul 2023 - Jul 2023]{.resume-date}
:::
::: {.resume-subtext}
MéridaLabs, Dept. of Mechanical Engineering, University of British Columbia
:::

* Collaborated with two co-op students to build a JavaScript/Svelte Smart Hydrogen Energy District website
* Reworked 3D models, produced renders and animations in AutoCAD for a national technology conference

::: {.resume-section-title}
PUBLICATIONS AND PRESENTATIONS
:::

**Poster/Presenter:** “Integrating Laser Speckle Contrast Imaging with OpenIVIS,” **Ko, N.**, Tran, M., Brake, J. Southern California Conference for Undergraduate Research, Nov 2025

**Poster/Presenter:** “Open-source bioluminescence imaging for low-light biological applications using the OpenIVIS platform,” Tran, M., **Ko, N.**, Brake, J. Southern California Conference for Undergraduate Research, Nov 2025

**Publication:** **Ko, N. M. T.** (2024). An evaluation of the adhesive capabilities of dry adhesive gecko tapes produced using diffraction gratings. STEM Fellowship Journal, e-First.  https://doi.org/10.17975/sfj-2024-002

::: {.resume-section-title}
VOLUNTEERING
:::

::: {.resume-row}
[Unpaid Engineering Tutor]{.resume-bold-title}

[Aug 2026 - Present]{.resume-date}
:::
::: {.resume-subtext}
Tau Beta Pi (California Omega Chapter), Harvey Mudd College
:::

* Provided free tutoring services for students in core Engineering courses for 1 hour per week

:::

:::